### ISSUE TITLE
Edit registration needs to allow current uname/email

### ISSUE THREAD

**Issue by eawoods** [arXiv/arxiv-auth#15]
Tried to edit my profile, form throws validation errors for username/email already in existence.

**Comment by HaHaBlah1** [comment]
> Tried to edit my profile, form throws validation errors for username/email already in existence.

**Comment by HaHaBlah1** [comment]
#91

**Comment by HaHaBlah1** [comment]
```html

```

**Comment by bdc34** [comment]
Code for this will be in another repo.
