### ISSUE TITLE
Vulnerability - private disclosure?

### ISSUE THREAD

**Issue by edent** [arXiv/arxiv-auth#89]
**Describe the bug**
I've found an open redirect vulnerability in arXiv's authentication page.  Is there a way to responsibly disclose it to you in private?  If not, are you happy for me to post it in the open here?

**Comment by bdc34** [comment]
I'd like to discuss it in private. Please contact me at the @cornell.edu email in my profile.

**Comment by bdc34** [comment]
Thanks, this can be reproduced and I have a fix. Will deploy soon.

**Comment by bdc34** [comment]
Added a fix for the most recent private communication from @edent
